[project]
name = "unit-robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "uncoffee", email = "shinohara.souta@it-mirai-h.ibk.ed.jp" }
]
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=5.0.0.93",
    "smbus2>=0.6.1",
]

[project.scripts]
unit-robot = "unit_robot:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
